# Docker compose configuration for development.

version: '3.8'
services:
  web:
    build: ./src
    expose:
      - 8000
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    command: gunicorn app.wsgi --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env.prod

  db:
    image: postgres:14-alpine
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file: .env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  prod_postgres_data:
  static_volume:
  media_volume:
