version: '3.8'
services:
  web:
    build: ./src
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env.prod

  db:
    image: postgres:14-alpine
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file: .env.prod
volumes:
  prod_postgres_data:
