# Generated by Django 4.1.1 on 2022-10-23 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_date_replenished_replenishment_time_replenished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replenishment',
            name='time_replenished',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='time_transfered',
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
