# Generated by Django 4.1.1 on 2022-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_remove_replenishment_time_replenished_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='negative_balance'),
        ),
    ]
