# Generated by Django 4.1.1 on 2022-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_account_negative_balance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='replenishment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='negative_amount_replenishment'),
        ),
    ]
